# Generated by Django 6.1.1 on 2026-09-13 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abrit_agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tool_identifier", models.CharField(max_length=255)),
                ("policy", models.CharField(max_length=50)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_policies",
                        to="abrit_agent.workspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "tool_identifier")},
            },
        ),
    ]
