# Generated by Django 6.1.1 on 2026-09-13 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STRUCTURE", "Structure"),
                            ("HOOK", "Hook"),
                            ("TONE", "Tone"),
                            ("CTA", "Call to Action"),
                            ("VISUAL", "Visual"),
                            ("SIMPLIFICATION", "Concept Simplification"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CANDIDATE", "Candidate"),
                            ("APPROVED", "Approved (Library Entry)"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="CANDIDATE",
                        max_length=50,
                    ),
                ),
                (
                    "applicable_platforms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of applicable platforms",
                    ),
                ),
                (
                    "applicable_content_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of applicable content categories",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tags/topics"
                    ),
                ),
                ("structured_attributes", models.JSONField(blank=True, default=dict)),
                (
                    "ai_consumable_representation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Normalized format for AI use",
                    ),
                ),
                (
                    "quality_confidence",
                    models.FloatField(
                        default=0.0, help_text="0.0 to 1.0 confidence score"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PatternEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relevance_score", models.FloatField(default=1.0)),
                ("extraction_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="patterns.contentpattern",
                    ),
                ),
                (
                    "research_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_evidence",
                        to="research.researchitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("pattern", "research_item")},
            },
        ),
    ]
