# Generated by Django 6.1.1 on 2026-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkspaceMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workspace_id", models.UUIDField(db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("writing_style", "WRITING_STYLE"),
                            ("preferred_tone", "PREFERRED_TONE"),
                            ("post_structures", "POST_STRUCTURES"),
                            ("previous_topics", "PREVIOUS_TOPICS"),
                            ("frequent_topics", "FREQUENT_TOPICS"),
                            ("unused_topics", "UNUSED_TOPICS"),
                            ("user_emphasis", "USER_EMPHASIS"),
                            ("edit_tendencies", "EDIT_TENDENCIES"),
                            ("cta_preferences", "CTA_PREFERENCES"),
                            ("visual_preferences", "VISUAL_PREFERENCES"),
                            ("brand_rules", "BRAND_RULES"),
                            ("previous_mistakes", "PREVIOUS_MISTAKES"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text_value", models.TextField(blank=True, null=True)),
                ("structured_value", models.JSONField(blank=True, null=True)),
                ("confidence", models.FloatField(default=1.0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "category"],
                        name="memory_work_workspa_c99f47_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "active"],
                        name="memory_work_workspa_33a946_idx",
                    ),
                ],
            },
        ),
    ]
