# Generated by Django 6.1.1 on 2026-09-13 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_content", models.TextField()),
                (
                    "reference_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "analysis_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ANALYZED", "Analyzed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from the source platform",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("error_metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workspace_id",
                    models.CharField(
                        help_text="Reference to external Workspace subsystem",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("TELEGRAM_CHANNEL", "Telegram Channel"),
                            ("TELEGRAM_GROUP", "Telegram Group"),
                            ("LINKEDIN", "LinkedIn"),
                            ("WORDPRESS", "WordPress"),
                            ("MANUAL", "Manual/Dataset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hook", models.TextField(blank=True, null=True)),
                ("tone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "length_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "headline_pattern",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "section_structure",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of structural elements",
                    ),
                ),
                (
                    "cta_pattern",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_angle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "concept_simplification_pattern",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "serialization_pattern",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "visual_strategy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "platform_specific_behavior",
                    models.JSONField(blank=True, default=dict),
                ),
                ("additional_attributes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="research.researchitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="researchitem",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="research.researchjob",
            ),
        ),
        migrations.AddField(
            model_name="researchjob",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="research.researchsource",
            ),
        ),
        migrations.AddField(
            model_name="researchitem",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="research.researchsource",
            ),
        ),
    ]
